export * from './Contato/Contato.jsx'
export * from './Footer/Footer.jsx'
export * from './Header/Header.jsx'
export * from './Home/Home.jsx'
export * from './Sobre/Sobre.jsx'
export * from './Cadastro/Cadastro.jsx'
export * from './Login/Login.jsx'
export * from './UserPage/UserPage.jsx'